events {}

http {
    upstream auth_service {
        server auth-service:8000;
    }

    upstream study_service {
        server study-service:8002;
    }

    upstream courses_service {
        server courses-service:8003;
    }

    upstream questions_service {
        server questions-service:8004;
    }

    upstream payments_service {
        server payments-service:8005;
    }

    upstream teachers_service {
        server teachers-service:8006;
    }

    server {
        listen 8000;

        location /health {
            return 200 '{"service":"api-gateway","status":"healthy"}';
            add_header Content-Type application/json;
        }

        location /api/v1/auth/ {
            proxy_pass http://auth_service/api/v1/users/;
        }

        location /api/v1/study/ {
            proxy_pass http://study_service/api/v1/study/;
        }

        location /api/v1/courses/ {
            proxy_pass http://courses_service/api/v1/courses/;
        }

        location /api/v1/questions/ {
            proxy_pass http://questions_service/api/v1/questions/;
        }

        location /api/v1/payments/ {
            proxy_pass http://payments_service/api/v1/payments/;
        }

        location /api/v1/teachers/ {
            proxy_pass http://teachers_service/api/v1/teachers/;
        }
    }
}